version: '3.8'

services:
  pitrain:
    build: .
    container_name: pitrain_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DATABASE_PATH=/data/pitrain.db
      - ALLOWED_ORIGINS=https://pitrain.waffelwurst.de
      - MISTRAL_TRANSCRIPTION_MODEL=voxtral-mini-latest
      - MISTRAL_EVALUATION_MODEL=mistral-small-latest
      - MISTRAL_BASE_URL=https://api.mistral.ai/v1
      - MAX_AUDIO_DURATION=900
      - MAX_FILE_SIZE=10485760
      - REQUEST_TIMEOUT=30000
      - RATE_LIMIT_WINDOW=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - LOG_LEVEL=info
    volumes:
      - ./data:/data
    networks:
      - waffelwurst_frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  waffelwurst_frontend:
    external: true